### ISSUE TITLE
Addon Name is wrong library instead of parts_library

### ISSUE THREAD

**Issue by claus007** [FreeCAD/FreeCAD-library#289] opened 2020-11-30 18:17 UTC
it is either wrong in your description or in the list...

btw. how do I get rid of the old one ?

**Comment by claus007** [comment] 2020-11-30 18:30
![Bildschirmfoto von 2020-11-30 19-26-46](https://user-images.githubusercontent.com/980684/100649296-878db000-3342-11eb-9c49-963a83caac04.png)

**Comment by normandc** [comment] 2021-03-07 08:33
Do you still have this issue? In my version of FreeCAD, the Add-on Manager correctly lists it as parts_library.

I would suggest you check into your Macro folder, maybe you have a duplicate of the parts_library.FCMacro macro renamed "library.FCMacro". The Macro dialogue will show where your Macro folder is located. https://wiki.freecadweb.org/Macros

**Comment by luzpaz** [comment] 2021-03-07 13:37
@claus007 
1. open you default FC directory (obtain your user's default FreeCAD folder by typing the following in to the FreeCAD Python console: `FreeCAD.ConfigGet("UserAppData")` on Linux it's `~/.FreeCAD` )
2. find the `Mod` subdirectory and open it
3. look for a folder called `library` and remove it

**Closed by luzpaz** 2021-03-07 13:37 UTC

**Comment by claus007** [comment] 2021-06-15 08:59
it's ok by now
![parts_02](https://user-images.githubusercontent.com/980684/122024457-bcd28a80-cdc8-11eb-8d44-8932b34026b4.png)
